micronaut:
  application:
    name: low-level-client-example
client:
  property:
    yaru:
      url: 'https://ya.ru'
    gcom:
      url: 'https://www.google.com'
    bing:
      url: 'https://www.bing.com'